#ifndef PINS_H
#define PINS_H

#include <TM4C123.h>



#define HCSR04_TIMER  ((TIMER0_Type*) TIMER0_BASE)
#define HCSR04_TIMER_NUM 0

#define HCSR04_TRIG_PIN_BASE_NUM 1                          
#define HCSR04_TRIG_PIN ((GPIOA_Type*) GPIOB_BASE)
#define HCSR04_TRIG_PIN_NUM 6

#define HCSR04_ECHO_PIN_BASE_NUM 1
#define HCSR04_ECHO_PIN ((GPIOA_Type*) GPIOB_BASE)
#define HCSR04_ECHO_PIN_NUM 7




#define KEYPAD_ENTER_PIN_BASE_NUM 3
#define KEYPAD_ENTER_PIN ((GPIOA_Type*) GPIOD_BASE)
#define KEYPAD_ENTER_PIN_NUM 3

#define KEYPAD_ROW_1_PIN_BASE_NUM 3
#define KEYPAD_ROW_1_PIN ((GPIOA_Type*) GPIOD_BASE)
#define KEYPAD_ROW_1_PIN_NUM 0

#define KEYPAD_ROW_2_PIN_BASE_NUM 3
#define KEYPAD_ROW_2_PIN ((GPIOA_Type*) GPIOD_BASE)
#define KEYPAD_ROW_2_PIN_NUM 1

#define KEYPAD_ROW_3_PIN_BASE_NUM 3
#define KEYPAD_ROW_3_PIN ((GPIOA_Type*) GPIOD_BASE)
#define KEYPAD_ROW_3_PIN_NUM 2



#define KEYPAD_COL_1_PIN_BASE_NUM 2
#define KEYPAD_COL_1_PIN ((GPIOA_Type*) GPIOC_BASE)
#define KEYPAD_COL_1_PIN_NUM 4

#define KEYPAD_COL_2_PIN_BASE_NUM 2
#define KEYPAD_COL_2_PIN ((GPIOA_Type*) GPIOC_BASE)
#define KEYPAD_COL_2_PIN_NUM 5

#define KEYPAD_COL_3_PIN_BASE_NUM 3
#define KEYPAD_COL_3_PIN ((GPIOA_Type*) GPIOD_BASE)
#define KEYPAD_COL_3_PIN_NUM 6

#define KEYPAD_COL_4_PIN_BASE_NUM 3
#define KEYPAD_COL_4_PIN ((GPIOA_Type*) GPIOD_BASE)
#define KEYPAD_COL_4_PIN_NUM 7

#define I2C_SCL_BASE GPIOB_BASE
#define I2C_SCL_NUM 2

#define I2C_SDA_BASE GPIOB_BASE
#define I2C_SDA_NUM 3


#define CHANGE_GRAPH_PIN_BASE_NUM 1
#define CHANGE_GRAPH_PIN ((GPIOA_Type*) GPIOB_BASE)
#define CHANGE_GRAPH_PIN_NUM 1

#define ONBOARD_LED_RED_PIN_BASE_NUM 5
#define ONBOARD_LED_RED_PIN ((GPIOA_Type*) GPIOF_BASE)
#define ONBOARD_LED_RED_PIN_NUM 1

#define ONBOARD_LED_BLUE_PIN_BASE_NUM 5
#define ONBOARD_LED_BLUE_PIN ((GPIOA_Type*) GPIOF_BASE)
#define ONBOARD_LED_BLUE_PIN_NUM 2

#define ONBOARD_LED_GREEN_PIN_BASE_NUM 5
#define ONBOARD_LED_GREEN_PIN ((GPIOA_Type*) GPIOF_BASE)
#define ONBOARD_LED_GREEN_PIN_NUM 3

#define BUZZER_PIN_BASE_NUM 1
#define BUZZER_PIN ((GPIOA_Type*) GPIOB_BASE)
#define BUZZER_PIN_NUM 0
/*


#deifne HCSR04_TRIG_PIN PB6 
#define HCSR04_ECHO_PIN PB7

#define ONBOARD_LED_RED PF1
#define ONBOARD_LED_BLUE PF2
#define ONBOARD_LED_GREEN PF3


#define LM35_PIN PC7 // ANALOG SIGNAL PIN  CONNECTED TO COMP0 cn+
#define LM35_COMPARATOR_PIN PF0 // ANALOG COMPARATOR OUTPUT PIN ---------LEAVE FLOATING
#define THRESHOLD_TRIMPOT_PIN PC6 // TRIMPOT ANALOG SIGNAL PIN CONNECTED TO COMP0 cn-

#define BUZZER_PIN PB0 // EXCHANGE WITH 5V Tolerant buzzer
#define POWERLED_PIN PB4C// LM35>THRESHOLD OLDUĞU DURUMDA ZATEN B PORTUNUN CLK SI FALAN AKTIF EDILCEK MIN ENERGY CONSUMPTION ICIN B PORT KULLANIYORUM

#define STEP_MOTOR_PIN_1 PE2 // MOTOR PINLERINI YAZDIM SIMDILIK AMA CAKISMA OLURSA DEISIRIZ NP, SADECE NE KULLANACAGIMIZ BELLI OLSUN DIYE DOLDURUYORUM
#define STEP_MOTOR_PIN_2 PE3
#define STEP_MOTOR_PIN_3 PE4
#define STEP_MOTOR_PIN_4 PE5



#define KEYPAD_ENTER_PIN PD3

#define KEYPAD_ROW_1 PD0
#define KEYPAD_ROW_2 PD1
#define KEYPAD_ROW_3 PD2
#define KEYPAD_COL_1 PC4
#define KEYPAD_COL_2 PC5
#define KEYPAD_COL_3 PD6
#define KEYPAD_COL_4 PD7



#define I2C_SCL PB2
#define I2C_SDA PB3

#define SPI_CLK PA2     //CLK
#define SPI_CS PA3      //CE
 #define SPI_MOSI PA5   //Din
 #define SPI_DC PA6     //DC   
#define SPI_RST PA7     //RST


//Boştaki pinler
PB1
PB5
*/

#endif 